In [11]:
import numpy as np

In [14]:
with open("data.txt") as file:
    inputs = file.readlines()
inputs = np.array([int(input) for input in inputs])

In [19]:
sums = inputs.reshape(-1, 1) + inputs.reshape(1, -1)
np.where(sums == 2020)

(array([ 64, 140]), array([140,  64]))

In [20]:
inputs[64] * inputs[140]

618144

In [21]:
# part 2
sums = inputs.reshape(-1, 1, 1) + inputs.reshape(1, -1, 1) + inputs.reshape(1, 1, -1)
np.where(sums == 2020)

(array([109, 109, 163, 163, 181, 181]),
 array([163, 181, 109, 181, 109, 163]),
 array([181, 163, 181, 109, 163, 109]))

In [24]:
inputs[109] * inputs[163] * inputs[181]

173538720